tutorials/developers/tutorial_01/tutorial_01.cpp
It seems the assumption is outdated. There is no invariant N in the code.
=> Tutorial comment fix

CMakeLists.txt, configure.cmake
Removes the default libpng dependency. Tested on VMs with and without libpng library.
=> Fixing libpng dependency

tutorials/developers/tutorial_01/tutorial_01.cpp, tutorials/developers/tutorial_01/wrapper_tutorial_01.cpp
Align with the issue https://github.com/Tiramisu-Compiler/tiramisu/issues/47, changing tutorial 01 to single dimension to make it simpler and correct. 2 dimensional case and Halide difference in indices will be handled in the second tutorial.
Tutorial passes.
=> Making tutorial_01 1 dimensional

tutorials/developers/tutorial_03/wrapper_tutorial_03.cpp
Align with issue https://github.com/Tiramisu-Compiler/tiramisu/issues/47, fixing tutorial 3. Even though it was wrong, the tutorial was passing initially because of the trivial input case.
Tutorial (correctly) passes now.
=> Fixing tutorial 3

src/tiramisu_codegen_cuda.cpp
Removing arch flag. Also removing optimizer flag since O3 is default.
=> CUDA arch fix

tutorials/developers/tutorial_04gpu/tutorial_04gpu.cpp
=> GPU tutorial fix

benchmarks/linear_algebra/blas/level3/sgemm/gpu/README.md, benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h, benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator.cpp, benchmarks/linear_algebra/blas/level3/sgemm/gpu/makefile, benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.cpp
Updating GPU sgemm benchmark. Current state:
| |Tiramisu|cublas|
|-|-------|-------|
|10 runs|~35-40ms|~6-7ms|
|Kernel time of single run (nvprof)|~36ms|~1.7ms|
=> GPU Gemm benchmark update

src/tiramisu_codegen_cuda.cpp
Removing unnecessary print statements from cuda codegen
=> Remove cuda prints

benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h, benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator.cpp, include/tiramisu/core.h, include/tiramisu/expr.h, src/tiramisu_core.cpp
Also updating GEMM benchmark so it completely uses new API. I will add tests in the next diff.
Builds without errors. All tests pass.
=> Fixed expr::to_str, added expr support for store_in

benchmarks/linear_algebra/blas/level3/sequential/gpu/README.md, benchmarks/linear_algebra/blas/level3/sequential/gpu/configuration.h, benchmarks/linear_algebra/blas/level3/sequential/gpu/generator.cpp, benchmarks/linear_algebra/blas/level3/sequential/gpu/makefile, benchmarks/linear_algebra/blas/level3/sequential/gpu/wrapper.cpp, benchmarks/linear_algebra/blas/level3/sequential/gpu/wrapper.h
GPU implementation of three matrix multiplication: AxBxC. Uses basic gpu tiling.
=> Sequential gemm base implementation

src/tiramisu_core.cpp
Fixing the computation::split bug.
All tests pass. All (runnable) benchmarks run.
=> Split bugfix

benchmarks/linear_algebra/chain_mm/gpu/configuration.h, benchmarks/linear_algebra/chain_mm/gpu/generator.cpp, benchmarks/linear_algebra/chain_mm/gpu/wrapper.cpp
Adding non-square matrix support for chain_mm_gpu and cublas multiplication for comparison.
I also tried basic fusion for the first loop level which reduced the performance so I'm not adding it. I'll keep experimenting with fusions.
=> chain_mm_gpu changes

benchmarks/linear_algebra/blas/level3/sgemm/gpu/CMakeLists.txt, benchmarks/linear_algebra/blas/level3/sgemm/gpu/README.md, benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h, benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator3.cpp, benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.cpp
Chaging gpu_gemm back to row-major inputs. There's no noticeable performance decrease. Also, changing benchmark output to median from mean.
=> gpu_gemm TMM -> MM

benchmarks/benchmark_list.txt, benchmarks/halide/edgegpu_ref.cpp, benchmarks/halide/edgegpu_tiramisu.cpp, benchmarks/halide/gaussiangpu_tiramisu.cpp, benchmarks/halide/wrapper_edgegpu.cpp, benchmarks/halide/wrapper_edgegpu.h
Basic GPU version of edge detection is added. Gaussian benchmark fixed.
Benchmarks pass.
=> Halide benchmark fixes

benchmarks/framework_benchmarking/image_processing/fusion/fusion.c, benchmarks/framework_benchmarking/image_processing/fusion/fusion.h, benchmarks/framework_benchmarking/image_processing/fusion/wrapper_fusion.cpp
Making PPCG fusion benchmark equivalent to halide benchmarks. Runs for both CPU and GPU.
=> Fix PPCG fusion bench

benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h, benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator3.cpp, benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.cpp, benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.h
Adding alpha-beta as parameter to the function instead of macro constant. There is no significant performance change.
=> GPU GEMM Alpha Beta

benchmarks/linear_algebra/blas/level3/sgemm/gpu/CMakeLists.txt, benchmarks/linear_algebra/chain_mm/gpu/CMakeLists.txt
Old linking doesn't work on fresh installation.
=> Use CMake linking for GPU

benchmarks/benchmark_list.txt, benchmarks/halide/heat3ddist_ref.cpp, benchmarks/halide/heat3ddist_tiramisu.cpp, benchmarks/halide/wrapper_heat3ddist.cpp, benchmarks/halide/wrapper_heat3ddist.h
=> Add heat3ddist benchmark

benchmarks/DNN/blocks/fusedresNet/configure.h, benchmarks/DNN/blocks/fusedresNet/fused_resnet_block_generator_mkldnn.cpp, benchmarks/DNN/blocks/fusedresNet/fused_resnet_block_generator_tiramisu.cpp, benchmarks/DNN/blocks/fusedresNet/wrapper_nn_block.cpp
- Correctness test changed from comparing strings to values
- Added ResNet schedule before fusing convolution and bn layers
=> Fused ResNet updates

src/tiramisu_codegen_halide.cpp, src/tiramisu_core.cpp, tests/test_163.cpp, tests/test_list.disabled, tests/wrapper_test_163.cpp, tests/wrapper_test_163.h
test_163 detects the constant access bug we have currently. It is disabled for now. We should reenable when we fix it.
Also, adding/removing some debug statements.
=> Adding failing test_163

benchmarks/DNN/blocks/LSTM/gpu_lib/generator.cpp, benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.cpp, benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.h, include/tiramisu/core.h, include/tiramisu/expr.h, include/tiramisu/type.h, src/tiramisu_codegen_cuda.cpp, src/tiramisu_codegen_halide.cpp, src/tiramisu_core.cpp, src/tiramisu_cuda_wrappers.cpp, src/tiramisu_expr.cpp
Please review https://github.com/Tiramisu-Compiler/tiramisu/pull/209 first.
Cleaning up the benchmark. Using new buffer API, merging some buffers and computations, adding documentation. Checked correctness up to floating point accuracy.
=> Lstm_lib cleanup

benchmarks/linear_algebra/blas/level2/gemv/gemv_generator.cpp, benchmarks/linear_algebra/blas/level2/gemv/gemv_wrapper.cpp
Hi,
Please find my implementation of GEMV level2 BLAS function. The code performs 
out = alpha * A * x + beta * y
Where 
**A** is a M x N matrix
**x** is a size N vector
**y** is a size M vector
**alpha**, **beta** are scalars
Thank you.
=> Added BLAS level2 function GEMV to the linear algebra benchmarks

benchmarks/linear_algebra/blas/level2/gemv/gemv_generator.cpp, benchmarks/linear_algebra/blas/level2/gemv/gemv_wrapper.cpp
Hi,
I have fixed the conding style issues.
Thanks.
=> Fix code structure

benchmarks/DNN/blocks/DenseNetBlock/densenet_block_generator_mkl.c, benchmarks/DNN/blocks/DenseNetBlock/wrapper_nn_block.cpp, benchmarks/DNN/blocks/fusedresNet/fused_resnet_block_generator_mkl.c, benchmarks/DNN/blocks/fusedresNet/fused_resnet_block_generator_mkldnn.cpp, benchmarks/DNN/blocks/fusedresNet/wrapper_nn_block.cpp, benchmarks/DNN/layers/bn/cpu/bn_layer_generator_mkl.c, benchmarks/DNN/layers/bn/cpu/bn_layer_generator_mkldnn.cpp, benchmarks/DNN/layers/bn/cpu/wrapper_nn.cpp
I have edited the thresholds used in the comparison of results for BN and ResNet.
=> Edit thresholds (BN and ResNet)

benchmarks/linear_algebra/blas/level3/symm/symm_generator.cpp, benchmarks/linear_algebra/blas/level3/symm/symm_wrapper.cpp
The symm generator is not yet optimized.
=> Add symm BLAS function

benchmarks/linear_algebra/blas/level1/asum/asum_generator.cpp, benchmarks/linear_algebra/blas/level1/asum/asum_wrapper.cpp, benchmarks/linear_algebra/blas/level2/syr/syr_generator.cpp, benchmarks/linear_algebra/blas/level2/syr/syr_wrapper.cpp
SYR performs the symmetric rank 1 operation:
`A := alpha * x * x**T + A`
Where: 
- alpha is a real scalar
- x is an n element vector
- A is an n by n symmetric matrix
ASUM performs the sum of the absolute values.
`sum(abs(x))`
Where:
- x is an (1 + ( N - 1 ) * abs(incx)) vector    
- incx storage spacing between elements of X
=> Add SYR BLAS function with basic optimization, ASUM BLAS function without optimisation

benchmarks/linear_algebra/blas/level1/copy/copy_generator.cpp, benchmarks/linear_algebra/blas/level1/copy/copy_wrapper.cpp, benchmarks/linear_algebra/blas/level1/swap/swap_generator.cpp, benchmarks/linear_algebra/blas/level1/swap/swap_wrapper.cpp, benchmarks/linear_algebra/blas/level2/syr2/syr2_generator.cpp, benchmarks/linear_algebra/blas/level2/syr2/syr2_wrapper.cpp
Add SYR2, COPY and SWAP BLAS functions with some basic optimizations to benchmarks
=> Add SYR2, COPY and SWAP BLAS functions with some basic optimizations to benchmarks

benchmarks/DNN/blocks/Conv-ReLU-MaxPool/conv_relu_maxpool_generator_tiramisu.cpp
Numbers : https://docs.google.com/spreadsheets/d/18nbTBRIBDAmohslrup8Vs3ri-TgYpOh6SzI8ttzWn0o/edit?usp=sharing
Pseudocode : https://docs.google.com/document/d/1B0M-KnAisEUXoYuL5K_msVR5in3cLTn7mzRnWcq_KYc/edit?usp=sharing (page 2)
=>  Conv-ReLU-MaxPool : fuse conv with maxpool 

benchmarks/DNN/layers/convolution/direct/cpu_bis/conv_layer_generator_tiramisu.cpp
Optimization is as follow:
Split dimension **x** to **x_b** and **xx**, and move **xx** to the inner loops.
=> Convolution : optimize for 3 input channels

include/tiramisu/expr.h
=> expr.h : translate equality to = instead of ==

utils/code_generator/time_measurement/filter_schedules.py
This script works for the multiple computations case, where the computations reside in the innermost loop level.
=> Autoscheduling : add a script that filter schedules

README.md
README.md: Avoid confusing a note as a shell command
=> README.md: Avoid confusing a note as command

tutorials/developers/tutorial_08/tutorial_08.cpp
Fix tutorial_08 error comment.
The kernel computation being implemented is output[i, j] = input[i, j] + i + 4.
=> Fix tutorial_08 error comment.

benchmarks/tensors/dibaryon/gpu_tiramisu_make_fused_dibaryon_blocks_correlator/README.md, include/tiramisu/cuda_ast.h, src/tiramisu_codegen_cuda.cpp
This patch fixes one thing I missed when summing the changes to push into tiramisu previously.
=> Fix buffer access

tutorials/developers/tutorial_01/tutorial_01.cpp
A couple of typos found in the tutorial file.
=> Fixed typos in toturial source file

include/tiramisu/core.h, src/tiramisu_core.cpp, src/tiramisu_function.cpp
=> 3D skewing

include/tiramisu/debug.h
Remove default debugging Halide output
=> Remove default debugging output
