Tiramisu-Compiler/tiramisu

tutorials/tutorial_02.cpp
tutorials/wrapper_tutorial_03.cpp

For tutorial 2, removed the confusing var("i") and var("j") redundancy.
For tutorial 3 wrapper, added initialization for C2_buf to 0 so that
tests pass.

Fixed tutorials 2 and 3

---

tutorials/developers/tutorial_02/tutorial_02.cpp
tutorials/developers/tutorial_02/wrapper_tutorial_02.cpp
tutorials/developers/tutorial_02/wrapper_tutorial_02.h

Align with https://github.com/Tiramisu-Compiler/tiramisu/issues/47, replacing tutorial 02 with a simpler tutorial that shows the index convention difference between Halide and Tiramisu.
Tutorial passes.

Fixing Tutorial 02

---

src/tiramisu_codegen_halide_lowering.cpp
src/tiramisu_core.cpp
src/tiramisu_mpi.cpp

I was going to work on https://github.com/Tiramisu-Compiler/tiramisu/issues/51 but I realized there are many whitespace inconsistencies which would make the diff complicated so I decided to fix the whitespace first. We seem to have tabs=4-spaces convention, but there was tab characters here and there that I'm fixing with this commit. This is a long diff, but it only contains whitespace changes.
Builds without errors. All tests pass.

Whitespace fixes, formatting

---

include/tiramisu/core.h
src/tiramisu_core.cpp

Fixes https://github.com/Tiramisu-Compiler/tiramisu/issues/60. Note that these are just wrappers and argument validity is not checked since the check is done by `tile` and `tag_gpu_level` functions.

Add gpu_tile overloads

---

benchmarks/linear_algebra/blas/level3/sgemm/gpu/README.md
benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h
benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator.cpp
benchmarks/linear_algebra/blas/level3/sgemm/gpu/makefile
benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.cpp

- Fixed generator so it works for non-square matrices as well.
- Fixed an issue in cublas call so now resulting matrices are exactly same in cublas.
- Reduced shared memory bank conflict (~15% improvement).

GPU Gemm Update

---

include/tiramisu/debug.h
include/tiramisu/expr.h
include/tiramisu/utils.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_codegen_from_halide.cpp
src/tiramisu_codegen_halide.cpp
src/tiramisu_core.cpp
src/tiramisu_debug.cpp

Replacing the tiramisu::error function with ERROR macro so that now it correctly prints the file and line number of the error location.
Builds without errors.

Error function fix

---

.gitmodules

Git commands like `status` and `checkout` take too long to run especially on remote servers because llvm and clang submodules are huge. Adding `ignore = all` property to submodules so git doesn't check there modules when executing commands.
A fresh copy builds without errors (including install_submodules.sh) and all tests pass.

Gitmodules ignore

---

include/tiramisu/core.h
include/tiramisu/cuda_ast.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_core.cpp

Adding `buffer::tag_gpu_local` to be able to create GPU thread local array.
Builds without errors. I'll add benchmarks using local memory.

GPU Local buffer

---

benchmarks/linear_algebra/blas/level3/sgemm/gpu/CMakeLists.txt
benchmarks/linear_algebra/blas/level3/sgemm/gpu/README.md
benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h
benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator2.cpp
benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator3.cpp
benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.cpp

Updating GPU GEMM Benchmark to use both shared and register tiling. Also changing spec to use transposed matrix multiplication where matrix B is assumed to be transposed already.
With input matrices of size 4096x4096:
|                               | cublas  | Tiramisu |
|-------------------------------|---------|----------|
| Single Run GPU Kernel Time    | 73.5ms  | 183ms    |
| 100 Runs Average CPU+GPU Time | 105.8ms | 172.7ms  |
Kernel time measurement has profiler overhead and doing more runs reduces the average time, but I'm not sure about the reason why cublas CPU overhead is bigger.
There's room for improvement for tuning parameters, prefetching, and optimizing memory access patterns.

GPU GEMM Benchmark Updates

---

src/tiramisu_core.cpp

computation constructors miss `DEBUG_INDENT(-4);` statements which makes debug indentation explode and hard to read. Adding them on lines 6160 and 6180. Also fixing some tabs to spaces. All changes are whitespace except two debug lines.

Fix Debug Indentation and Whitespace

---

utils/scripts/install_submodules.sh

Built with NVPTX on computers with and without CUDA support. Benchmarks run for both.

Build llvm with nvptx by default

---

.travis.yml
src/tiramisu_codegen_halide.cpp

Now that we switched to AVX from AVX2 with commit https://github.com/Tiramisu-Compiler/tiramisu/commit/7274375cd5e85500119a8c2e68fc7d6619e88a95, we can enable Travis to run the `make test` to assure that tests pass. This increases build time by about 10-12 mins.

Enable Travis tests

---

benchmarks/linear_algebra/blas/level3/sgemm/gpu/configuration.h

Reducing the register tile size from 12x16 to 6x16 gives marginal improvement: 77ms -> 73ms. This might be an indicator that some memory copy is slow. I'll look into that.
Interestingly, tile size 8x16 is slower than both (83ms) even though it's in the middle.

GPU GEMM Tiling update

---

benchmarks/linear_algebra/blas/level3/sgemm/gpu/CMakeLists.txt
benchmarks/linear_algebra/blas/level3/sgemm/gpu/generator3.cpp
benchmarks/linear_algebra/blas/level3/sgemm/gpu/wrapper.cpp

Adding prefetching and global memory coalescing on warp level to GPU Gemm.
I realized the kernel run time doesn't reach steady state for 10-15 runs. So I've increased the warm up runs. I've also fixed a global memory coalescing issue I found in profiler. Here are the latest numbers (GPU time, 3072x3072):
|                 | Pascal 4 | Kepler 80 (Salike) |
|-----------------|----------|--------------------|
| Old             | 20ms     | 73ms               |
| After Prefetch  | 19.2ms   | 74.5ms             |
| **After Coalescing** | **18.3ms**   | **62.5ms**             |
| cuBLAS          | 10.8ms   | 28ms               |
Note that unlike P4, prefetching decreases the performance slightly on K80. But combined, we get improvements of 9% on P4 and 15% on K80 with this diff.
**Next steps:** …

GPU Gemm Improvements

---

include/tiramisu/core.h
include/tiramisu/cuda_ast.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_codegen_halide.cpp

Removing isl_ast_node_ptr and using direct isl_ast_node*'s to map kernels to loops. Also adding wrapping loop iterators to kernels as arguments.
I will add a test for this fix as well.

Fix GPU Kernel bugs

---

include/tiramisu/core.h
include/tiramisu/cuda_ast.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_codegen_halide.cpp

Cleaning up after kernel map patch. Removing unnecessary parameters, fixing map type.
Tested with GPU benchmarks.

GPU Iterator map cleanup

---

benchmarks/DNN/blocks/LSTM/gpu/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu/wrapper.cpp

Adding shared memory to GEMM's in LSTM. This improves the performance by about 7x. I haven't analyzed coalescing and implemented register blocking yet so there's room for improvement.
The program runs in ~140ms on K80. The Nvidia blog post's baseline is 310ms and their end result is 28ms on an M40.

LSTM GPU Update

---

CMakeLists.txt
benchmarks/DNN/blocks/LSTM/gpu/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu/wrapper.cpp

Changing LSTM GEMM tile size to 8, which gives huge improvement! Also fixing a CMake bug.
I tried skewing with inner loop parallelization as well but it doesn't seem to give any improvement. It probably requires CUDA streams for parallelization (which we don't have). 
The previous benchmarks were on Salike. I switched to Pascal4 (Google cloud) for benchmarks and it's actually pretty close to Nvidia blogpost with this last change:
| Program   | Time  |
|-----------------|-------|
| Old (16 tile)   | 87ms  |
| New (8 tile)    | ~38ms |
| Nvidia Blogpost | ~35ms |
Also Nvidia's code runs slower than they reported (27.8ms). Their run was on Maxwell40, which is an older architecture but maybe it's better than Pascal4.
Finally, I tried to implement a cuDNN benchmark directly from library, but …

LSTM tile size

---

tutorials/developers/tutorial_01/tutorial_01.cpp

corrected path to isl library: libisl.so is in 3rdParty/isl/build/lib. This was causing manual compilation to fail on machines that don't have the isl lib installed globally. removed linking to isl library in wrapper compilation, as wrapper doesn't use it, and compilation fails if path to isl/build/lib is not given.

corrected path to isl library in tutorial01 

---

CMakeLists.txt
benchmarks/DNN/blocks/LSTM/cpu/generator.cpp
benchmarks/DNN/blocks/LSTM/cpu/wrapper.cpp
benchmarks/DNN/blocks/LSTM/gpu/CMakeLists.txt
benchmarks/DNN/blocks/LSTM/gpu/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu/reference_generator.cpp
benchmarks/DNN/blocks/LSTM/gpu/wrapper.cpp
benchmarks/DNN/blocks/LSTM/gpu/wrapper.h

Adding reference implementation for correctness check of LSTM gpu. Also fixing an off-by-one error. There is a race condition in current gpu implementation and thus correctness check don't pass. Will fix it soon.
Also disabling LSTM by default since Cmake fails on systems with cuda but no cudnn.

LSTM Correctness progress

---

benchmarks/DNN/blocks/LSTM/gpu_lib/CMakeLists.txt
benchmarks/DNN/blocks/LSTM/gpu_lib/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/reference_generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.cpp
include/tiramisu/core.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_core.cpp
src/tiramisu_expr.cpp

- 18ce3a1 fixes the bug that prevents using o_call with gpu code generation.
- 61ed24d adds a simple check to `cublas_sgemm` to make sure matrices you are multiplying are on GPU memory.
- e874c86 and 14889dc modifies LSTM gpu_lib benchmark to make a basic map to GPU and make sure reference and benchmark output agree.
- c61e6a1 replaces gemm in LSTM with `cublas_sgemm`. Due to floating point errors, output starts to diverge with respect to reference as network gets more layers and sequences, but for small sizes it agrees with the reference up to a small error margin.
Next, I will optimize some of the kernels and check the speed compared to cuDNN and other implementations.

LSTM_lib Progress

---

benchmarks/DNN/blocks/LSTM/gpu_lib/CMakeLists.txt
benchmarks/DNN/blocks/LSTM/gpu_lib/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/reference_generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.cpp
include/tiramisu/core.h
include/tiramisu/cuda_ast.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_core.cpp
src/tiramisu_expr.cpp

Please review https://github.com/Tiramisu-Compiler/tiramisu/pull/202 first.
Fixes some indentation issues of `cuda_ast.h`. Also simplifies namespace structure of `tiramisu_codegen_cuda.cpp`. No functionality changed. Only whitespace and namespace changes.
The half of `tiramisu_codegen_cuda.cpp` is in wrong indentation. I don't want to change it in one shot since it confuses git-diff and makes it very difficult to track changes through git-blame. I will fix indentations as I make changes to functions.
GPU tests succeed. Please wait for Travis tests to pass as well.

cuda_ast formatting

---

benchmarks/DNN/blocks/LSTM/gpu_lib/CMakeLists.txt
benchmarks/DNN/blocks/LSTM/gpu_lib/configuration.h
benchmarks/DNN/blocks/LSTM/gpu_lib/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.cpp

Several optimizations for LSTM with cuBLAS benchmark including batched GEMM, loop interchange, and fusion. Correctness test passes with small margin of floating point arithmetic error. The latest numbers are:
`filter x batch x layer x sequence = 512 x 64 x 4 x 100`:
Tiramisu: 114.2ms (vs. previous PR: 162.2ms)
cuDNN: 54.3ms
The next big improvement will be to use streaming API to increase parallelism. There seems to be a simple way to get this via parallelizing kernel calls, but this doesn't work since loop tagging API we have is not compatible with cuda API (it's actually a more general problem). Let's discuss this when we meet.

LSTM_cublas Optimizations

---

benchmarks/DNN/blocks/LSTM/gpu_lib/CMakeLists.txt
benchmarks/DNN/blocks/LSTM/gpu_lib/configuration.h
benchmarks/DNN/blocks/LSTM/gpu_lib/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.cpp
src/tiramisu_codegen_cuda.cpp

Please review https://github.com/Tiramisu-Compiler/tiramisu/pull/204 first.
Some formatting fixes for `tiramisu_codegen_cuda.cpp` to make it more coherent and understandable. No functionality changed, only curly braces and whitespace. Again, there's a lot more to fix but I don't want to edit the whole file to not to mess up with the git-blame history.

Cuda_ast formatting fixes

---

include/tiramisu/core.h
include/tiramisu/expr.h
include/tiramisu/type.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_codegen_halide.cpp
src/tiramisu_core.cpp
src/tiramisu_cuda_wrappers.cpp
src/tiramisu_expr.cpp

I figured out that parallelization of kernels wasn't working because of a cascade of type bugs in cuda_ast. This PR introduces kernel streaming API and does several fixes to do so:
- Adds the helper function `extract_tags_from_isl_node` to `tiramisu_codegen_halide.cpp`, which traverses the given subtree in ISL AST and fills the `tagged_stmts` vector. This function is used while codegen replaces for loops with GPU kernel calls to make sure we don't lose tags inside kernels.
- Adds `p_void_ptr` data type to `primitive_t`, which is used to represent raw buffers. This type is casted to Halide type `Halide::type_of<void*>()` during codegen.
- This is required since buffers are passed as regular variables when calling cuda helper functions. Previously type of the buffer variables were wrongly …

Fix cuda type bugs, add cuda streams API, parallel kernels

---

benchmarks/DNN/blocks/LSTM/gpu_lib/generator.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.cpp
benchmarks/DNN/blocks/LSTM/gpu_lib/wrapper.h
include/tiramisu/core.h
include/tiramisu/expr.h
include/tiramisu/type.h
src/tiramisu_codegen_cuda.cpp
src/tiramisu_codegen_halide.cpp
src/tiramisu_core.cpp
src/tiramisu_cuda_wrappers.cpp
src/tiramisu_expr.cpp

Please review https://github.com/Tiramisu-Compiler/tiramisu/pull/208 first.
Adding several optimizations to LSTM-with-cuBLAS benchmark.
- Parallelize LSTM blocks with the new streams API
- Pretranspose weights
- Fuse some kernels
While analyzing the profiler data I realized that Tiramisu time includes the `cuda_malloc` and `cuda_free` times as well, which is quite significant (~30%). To eliminate this comparison difference with cuDNN, runtime is now calculated from within the Tiramisu function using an helper function. Now we are only measuring the GPU time - excluding malloc, memcpy, and etc. Results are pretty close to cuDNN:
GPU time of `filter x batch x layer x sequence = 512 x 64 x 4 x 100` on Salike(K80):
Tiramisu: 57.6ms
cuDNN: 50.4ms
Now we have all the optimizations mentioned in …

LSTM_cublas Benchmark Progress

---

README.md

Without absolute path as argument, the script fails to cd in llvm directory.

install_submodules.sh seems to need absolute path

---

benchmarks/DNN/blocks/DenseNetBlock/configure.h
benchmarks/DNN/blocks/DenseNetBlock/densenet_block_generator_tiramisu.cpp

I have added some simple optimizations to the DenseNet block benchmark :
1. Fuse some loops (Batch normalization and ReLU are now done in a single loop).
2. Unroll the inner-most level of the convolution loop (this level applies the convolution filter over the x-axis, it just does 3 iterations as the filter size is 3x3).
3. Tag two loop levels to be parallelized.
I have tested execution time with the following parameters : 
BATCH_SIZE = 32
Width and Height = 28
Input channels = 128
Output channels = 32
The results on my laptop are : 
Intel MKL : 256ms.
Tiramisu : 551ms.

Add simple optimizations to DenseNet block

---

benchmarks/DNN/blocks/DenseNetBlock/densenet_block_generator_tiramisu.cpp

I have added the convolution optimizations, and tagged a loop in batch normalization to be parallelized.
The convolution optimizations are : loop interchange, parallelize, split and vectorize. I have tried to tune the parameters according to the different sizes of the input.
For BN, I should see how to optimize it better.
Here are the results that I have, the input and output channels are always respectively 128 and 32. **N** represents the width and height of the input. As you see, for N = 7, Intel MKL code outperforms TIramisu code, I should investigate this.
-----------------------------------
BATCH_SIZE = 100
N = 56
MKL : 3366.581 ms
Tiramisu : 2075.63 ms
-----------------------------------
BATCH_SIZE = 32
N = 56
MKL : 1056.836 ms
Tiramisu : 666.363 ms …

Optimize convolution and BN in DenseNet block

---

benchmarks/DNN/blocks/DenseNetBlock/densenet_block_generator_tiramisu.cpp
benchmarks/DNN/blocks/DenseNetBlock/wrapper_nn_block.cpp

I have fused BN-ReLU with convolution and got an improvement in performance. You can see the new execution times in the spreadsheet.
I have first tried a simpler method for the fusion, you can find how it looks in the pseudocode. Now I will try the method with split to see if it improves results.
Spreadsheet : https://docs.google.com/spreadsheets/d/18nbTBRIBDAmohslrup8Vs3ri-TgYpOh6SzI8ttzWn0o/edit?usp=sharing
Pseudocode : https://docs.google.com/document/d/1B0M-KnAisEUXoYuL5K_msVR5in3cLTn7mzRnWcq_KYc/edit?usp=sharing

Fuse BN-ReLU with convolution in DenseNet block

---

src/tiramisu_codegen_cuda.cpp
src/tiramisu_codegen_halide_to_c.cpp
src/tiramisu_core.cpp
src/tiramisu_cuda_wrappers.cpp
src/tiramisu_debug.cpp
src/tiramisu_expr.cpp

Include files fix affect MSVC only.
Static initialization order fix affects both MSVC and MinGW GCC. Before that change there were some runtime errors at the library initialization stage:
https://isocpp.org/wiki/faq/ctors#static-init-order

Windows fix

---

benchmarks/linear_algebra/blas/level3/syrk/syrk_generator.cpp
benchmarks/linear_algebra/blas/level3/syrk/syrk_wrapper.cpp

Hi,
Here's my implementation of SYRK using the old Tiramisu syntax : 
out = alpha * A * A' + beta * C
I have tried using the new Tiramisu syntax but didn't find how to make variables iterate according to another variable's value. I've tried 
`var i("i", 0, N);`
`var j("j", 0, i);`
But i had to declare many variables to get different iteration domains. Which got me into problems later.
So I wanted to know if this is valid using the new syntax.
Thank you very much.

Add syrk BLAS function without optimizations

---

benchmarks/linear_algebra/blas/level2/gemv/gemv_generator.cpp
benchmarks/linear_algebra/blas/level3/syrk/syrk_generator.cpp

Hi,
I've added some optimizations to GEMV : 
- Parallelized the outer loop.
- Unrolled the cumulative loop for MatrixRow * vector.
For SYRK, I've :
- Parallelized the outer loop.
- Unrolled cumulative loop for MatrixRow * MatrixColumn
I've also tried to vectorize loop "j" on mat_mul. After testing, results seemed coherent. But i've found on the documentation that's not possible to vectorize loops with a number of interations less than the vector size, I preferred not to include it.
PS : the optimization I have tried is 
`mat_mul.vectorize(j, VECTOR_SIZE);`
Is it allowed ? Even though 
- 0 <= i < N 
- 0<= j <=i
And for i from 0 to VECTOR_SIZE -2, loop j will have less than VECTOR_SIZE iterations
Thank you

Add optimizations to syrk and gemv blas functions

---

benchmarks/DNN/blocks/DenseNetBlock/configure.h
benchmarks/DNN/blocks/DenseNetBlock/densenet_block_generator_tiramisu.cpp
benchmarks/DNN/blocks/DenseNetBlock/wrapper_nn_block.cpp

Here I have fused BN-ReLU with CONV. The fusion can be enabled or disabled via `config.h`. By default, I enable it for large values of **N** (width and height of input), as it improves performances only when **N** is large enough.
You can find the numbers here : https://docs.google.com/spreadsheets/d/18nbTBRIBDAmohslrup8Vs3ri-TgYpOh6SzI8ttzWn0o/edit?usp=sharing

DenseNet block : Fuse BN-ReLU with CONV

---

benchmarks/halide/resize_ref.cpp
benchmarks/halide/resize_tiramisu.cpp
benchmarks/halide/wrapper_resize.cpp

Here I have rewritten the resize benchmark. It only handles grayscale images, as the original one did.
Performances are as follow :
Tiramisu         ; Halide         ; 
10.439629      ; 11.172903      ;

Rewrite resize benchmark

---

benchmarks/DNN/blocks/Conv-ReLU-MaxPool/configure.h
benchmarks/DNN/blocks/Resize-Conv/configure.h
benchmarks/DNN/blocks/Resize-Conv/resize_conv_generator_mkldnn.cpp
benchmarks/DNN/blocks/Resize-Conv/resize_conv_generator_tiramisu.cpp
benchmarks/DNN/blocks/vggBlock/configure.h
benchmarks/DNN/blocks/vggBlock/vgg_block_generator_mkl.c
benchmarks/DNN/blocks/vggBlock/vgg_block_generator_mkldnn.cpp
benchmarks/DNN/blocks/vggBlock/vgg_block_generator_tiramisu.cpp
benchmarks/DNN/blocks/vggBlock/wrapper_nn_block.cpp
benchmarks/DNN/layers/convolution/direct/cpu_bis/configure.h

- In Resize-Conv, avoid changing the data layout of the input as this is not necessary in this case and this adds an overhead to execution time.
- Fuse Resize with Conv.
- Switch Conv-ReLU-MaxPool, Resize-Conv and Convolution to 32 output channels.
- Optimize vggBlock for 3 input channels.

Update DNN benchmarks

---

.gitmodules

Updated submodules URLs after LLVM code base migration from from git.llvm.org to github.com

Update submodules URL

---

src/tiramisu_codegen_halide.cpp

Our previous problem was tiling + skewing that causes segmentation error.
After deep investigation, the cause was an index out of bound error.
I compared ast from isl with halide IR, then I noticed that number of Min & Max in the code were missing.
the original code was limited to 2 min & max operands, this should not be the case.
As stated in isl documentation, min & max have 2 operands or MORE ...
this patch allows correct code generation and could solve many other issues that the cause was unknown.

code generation patch
